name: Build, Lint, and Upload Debug APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  build:
    name: Build Debug APK
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk-raw
          path: app/build/outputs/apk/debug/app-debug.apk

  upload-apk:
    name: Upload Debug APK as Artifact
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: debug-apk-raw
          path: extracted-apk

      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: extracted-apk/app-debug.apk
